# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: careconnect-tls
  namespace: careconnect
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: careconnect.laendletech.at
  dnsNames:
    - careconnect.laendletech.at